project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"
    - "*.ipynb"
    - "!contents/ignore/"
    - "!contents/Exams/"
    - "!contents/old/"
    - "!contents/Exercises/"
    - "!contents/Modelling/"
    - "!contents/Statisitcs/"
    - "!contents/Transform/"
    - "!contents//"
    - "!*.py"
    - "!final*.ipynb"
    - "!midterm*.ipynb"
    - "!overview*.ipynb"
    - "!slides/"
    - "!*-temp.ipynb"
    - "!*-temp.qmd"
  resources: CNAME
  preview:
    port: 5452

website:
  google-analytics: "G-5R1D200E6D"
  page-navigation: true
  bread-crumbs: false
  # navbar: true
  title: "{{< fa chart-simple >}} Data Analysis & Visualization"
  description: "Data Analysis and Visualization, Dongguk University, 2024-1"
  site-url: "https://dgdavs.modellings.art"
  site-path: "/"
  # repo-url:
  # repo-actions: [edit, issue]

  page-footer:
    # right: "This page is built with [Quarto](https://quarto.org/)."
    left: This work © 2024 by Sungkyun Cho is licensed under CC BY-NC-SA 4.0 
    # background: 

  sidebar:
    # background: "#F6F6FF"
    # logo: 
    # pinned: true
    alignment: left
    # tools:
    #   - icon: github
    #     href: 
    #     text: "GitHub organization"
    style: "floating"
    search: true
    collapse-level: 2
    
    contents:
      - href: index.qmd
        text: "{{< fa angles-right size=xs >}} Welcome"
      - href: contents/notice.qmd
        text: "{{< fa check size=xs >}} Notice"
      # - href: contents/vote.qmd
      #   text: "{{< fa magnifying-glass size=xs >}} 설문"
      # - href: contents/shortcuts.qmd
        # text: "{{< fa hourglass size=xs >}} 오늘의 숏컷"
      # - href: https://docs.google.com/document/d/1Yv78iYpRFfpEtPjSN6YRtX9iVAMhF_FgMgZRl2p88Bc/edit?usp=sharing
        # text: "{{< bi stopwatch >}} 기말고사 <<<<<<<<<<"
      - text: ---
      - section: Introduction
        contents:
          - href: contents/Introduction/intro2.qmd
            text: Data Analysis Intro
          - href: contents/Introduction/rethinking.qmd
            text: Statistical Thinking
          - href: contents/Introduction/setup.qmd
            text: Setup
          - section: contents/Introduction/pandas.ipynb
            contents: 
            - href: contents/Introduction/inspection.ipynb
          - href: contents/Introduction/vis.ipynb
            text: Data visualization
      - text: ---
      - section: Visualize
        contents:
          - href: contents/Visualize/seaborn.ipynb
            text: Seaborn.objects
          - section: contents/Visualize/plots.ipynb
            contents: 
              - href: contents/Visualize/alt_plots.ipynb
          - href: contents/Visualize/customizing.ipynb
      - text: ---
      - section: contents/EDA/eda.ipynb
        contents:
          - href: contents/EDA/discretize.ipynb
      # - text: ---
      # - section: Transform
      #   contents:
      #     - href: contents/Transform/subsetting.ipynb
      #       # contents:
      #       #   - href: contents/Transform/views.ipynb
      #     - href: contents/Transform/transform.ipynb
      #       contents:
      #         - href: contents/Transform/case1.ipynb
      #           text: Case Study 1
      #         - href: contents/Transform/babynames.ipynb
      #           text: Case Study 2
      #         - href: contents/Transform/exercise_transform.ipynb
      #     - section: Transforming II
      #       contents:
      #         - href: contents/Transform/combine.ipynb
      #         - href: contents/Transform/pivot.ipynb
      #         - href: contents/Transform/crosstab.ipynb
      #           text: Pivot Table
      #         - href: contents/Transform/exercise_wrangle.ipynb
      #     - href: contents/Transform/misc.ipynb
      #     # - section: Solutions
      #     #   contents:
      #     #     - href: contents/sol1.ipynb
      #     #     - href: contents/sol2.ipynb
      # - section: Exercises
      #   contents:
      #     - href: contents/Exercises/billboard.ipynb
      #       text: Billboard
      #     - href: contents/Exercises/movielens.ipynb
      #       text: MovieLens
      #     # - section: Solutions
      #     #   contents:
      #     #     - href: contents/billboard_sol.ipynb
      #     #     - href: contents/movielens_sol.ipynb
      # - text: ---
      # - section: contents/eda.ipynb
      #   contents:
      #     - href: contents/discretize.ipynb
      # # - text: ---
      # # - section: Modelling
      # #   contents:
      # #     - href: contents/model-basic.ipynb
      # #       text: Model Basics
      # #     - href: contents/modelling1.ipynb
      # #     - href: contents/modelling2.ipynb
      # #     - href: contents/logistic.ipynb
      # #   #   - section: Solutions
      # #   #     contents:
      # #   #       - href: contents/modelling1_ex.ipynb
      # #   #         text: Modelling 1 Ex.
      # #   #       - href: contents/modelling2_ex.ipynb
      # #   #         text: Modelling 2 Ex.
      # #   # #       # contents:
      # #   #       #   - href: contents/modelling3_ex.ipynb
      # #   #     #- href: contents/misc4.ipynb
      # # - text: ---
      # # - href: contents/statistics.ipynb
      - text: ---
      - section: Communicate
        contents:
          - href: https://docs.google.com/document/d/1g57REsUnvtSa1Yxr9WWP63yQivs4DO_0wVDHS9A3bO4/edit?usp=sharing
            text: Ask
          # - href: https://docs.google.com/document/d/13RYgzt7L4Bbw46kHHpQMNLXWJZMi62hJPk44TBoLteQ/edit?usp=sharing
          - text: Personal Project

  # navbar:
  #   left:
  #     - href: index.qmd
  #       text: Home
  #     - about.qmd

format:
  html:
        toc: true
        toc-depth: 4
        toc-location: right
        code-fold: false
        code-overflow: wrap
        code-summary: "Show the code"
        theme: [sandstone, theme-light.scss]
        fontsize: 1.1em
        linestretch: 2
        code-copy: true
        highlight-style: ayu-light
        link-external-newwindow: true
        bread-crumbs: false
        grid:
          body-width: 900px
          margin-width: 200px
        # grid:
        #   sidebar-width: 270px
        # css: styles.css



