project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"
    - "*.ipynb"
    - "!contents/ignore/"
    #- "!exercise*.ipynb"
    - "!contents/*.py"
    - "!final*.ipynb"
    - "!midterm*.ipynb"
    #- "!model*.ipynb"
    - "!statistic.ipynb"
    - "!overview*.ipynb"
  resources: CNAME
  preview:
    port: 5452

website:
  page-navigation: true
  # navbar: true
  title: "{{< fa chart-simple >}} Data Analysis & Visualization"
  description: "Data Analysis and Visualization, Dongguk University, 2023-2"

  # site-url:
  # repo-url:
  # repo-actions: [edit, issue]

  page-footer:
    # right: "This page is built with [Quarto](https://quarto.org/)."
    left: This work © 2023 by Sungkyun Cho is licensed under CC BY-NC-SA 4.0 
    # background: 

  sidebar:
    # background: "#F6F6FF"
    # logo: 
    pinned: true
    align: center
    # tools:
    #   - icon: github
    #     href: 
    #     text: "GitHub organization"
    style: "docked"
    search: true
    collapse-level: 1
    
    contents:
      - href: index.qmd
        text: "{{< fa angles-right size=xs >}} Welcome"
      - href: contents/notice.qmd
        text: "{{< fa check size=xs >}} Notice"
      - href: contents/vote.qmd
        text: "{{< fa magnifying-glass size=xs >}} 설문"
      - href: contents/shortcuts.qmd
        text: "{{< fa hourglass size=xs >}} 오늘의 숏컷"
      - text: ---
      - section: Introduction
        contents:
          - href: contents/intro.qmd
            text: Data Analysis Intro
          - href: contents/setup.ipynb
            text: Setup
          - section: contents/pandas.ipynb
            contents: 
            - href: contents/inspection.ipynb
          - href: contents/vis.ipynb
            text: Data visualization
      - text: ---
      - section: Visualize
        contents:
          - href: contents/seaborn.ipynb
            text: Seaborn.objects
          - section: contents/plots.ipynb
            contents: 
              - href: contents/alt_plots.ipynb
          - href: contents/customizing.ipynb
      - text: ---
      - section: Transform
        contents:
          - href: contents/subsetting.ipynb
            contents:
              - href: contents/views.ipynb
          - href: contents/transform.ipynb
            contents:
              - href: contents/case1.ipynb
                text: Case Study 1
              - href: contents/babynames.ipynb
                text: Case Study 2
              - href: contents/exercise_transform.ipynb
          - section: Transforming II
            contents:
              - href: contents/combine.ipynb
              - href: contents/pivot.ipynb
              - href: contents/crosstab.ipynb
                text: Pivot Table
              - href: contents/exercise_wrangle.ipynb
          - href: contents/misc.ipynb
          - section: Solutions
            contents:
              - href: contents/sol1.ipynb
              - href: contents/sol2.ipynb
      - section: Exercises
        contents:
          - href: contents/billboard.ipynb
            text: Billboard
          - href: contents/movielens.ipynb
            text: MovieLens
          - section: Solutions
            contents:
              - href: contents/billboard_sol.ipynb
              - href: contents/movielens_sol.ipynb
      - text: ---
      - section: contents/eda.ipynb
        contents:
          - href: contents/discretize.ipynb
      - text: ---
      - section: Modelling
        contents:
          - href: contents/model-basic.ipynb
            text: Model Basics
        #     - href: contents/modelling1.ipynb
        #     - href: contents/modelling2.ipynb
        #     - href: contents/logistic.ipynb
        #       # contents:
        #       #   - href: contents/modelling3_ex.ipynb
        #     #- href: contents/misc4.ipynb
        # - text: ---
        # - href: contents/statistics.ipynb
      - text: ---
      - section: Communicate
        contents:
          - href: https://docs.google.com/document/d/124YaRWnLf9ROgaGmepeU4tQvLpCIHFcdp4Ojocwrhmc/edit?usp=sharing
            text: Ask
          - href: https://docs.google.com/document/d/13RYgzt7L4Bbw46kHHpQMNLXWJZMi62hJPk44TBoLteQ/edit?usp=sharing
            text: Personal Project

  # navbar:
  #   left:
  #     - href: index.qmd
  #       text: Home
  #     - about.qmd

format:
  html:
        toc: true
        toc-depth: 4
        toc-location: right
        code-fold: false
        code-overflow: scroll
        code-summary: "Show the code"
        theme: [sandstone, theme-light.scss]
        fontsize: 1em
        linestretch: 1.8
        code-copy: true
        highlight-style: ayu-light
        link-external-newwindow: true
        bread-crumbs: false
        # grid:
        #   sidebar-width: 270px
        # css: styles.css



